/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventSlugRouteImport } from './routes/$eventSlug'
import { Route as IndexRouteImport } from './routes/index'

const EventSlugRoute = EventSlugRouteImport.update({
  id: '/$eventSlug',
  path: '/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$eventSlug': typeof EventSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$eventSlug': typeof EventSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$eventSlug': typeof EventSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$eventSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$eventSlug'
  id: '__root__' | '/' | '/$eventSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventSlugRoute: typeof EventSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$eventSlug': {
      id: '/$eventSlug'
      path: '/$eventSlug'
      fullPath: '/$eventSlug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventSlugRoute: EventSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
